version: "3"

services:
  nginx:
    container_name: privacy_policy
    image: nginx:latest
    working_dir: /home/privacy_policy
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ..:/home/privacy_policy
      - ../nginx-logs:/var/log/nginx
    ports:
      - 8079:80
